---
# handlers file for ansible-freeipa-client
#
- name: restart sssd (via upstart)
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=sssd
    state=restarted
    use=upstart
  ignore_errors=true

- name: restart sssd 
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=sssd
    state=restarted
  ignore_errors=true


- name: restart ssh
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=ssh
    state=restarted
