---
# handlers file for ansible-freeipa-client
#
- name: restart sssd (via service)
  listen: "restart sssd"
  tags:
    - sssd
    - freeipaclient
  become: true
  command: service sssd restart
  warn: false

- name: restart ssh (via service)
  listen: "restart ssh"
  tags:
    - sssd
    - freeipaclient
  become: true
  command: service ssh restart
  warn: false
