---
# handlers file for ansible-freeipa-client
#
- name: restart sssd (via upstart)
  listen: "restart sssd"
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=sssd
    state=restarted
    use=upstart
  ignore_errors: true

- name: restart sssd (via service)
  listen: "restart sssd"
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=sssd
    state=restarted
  ignore_errors: true

- name: restart ssh (via upstart)
  listen: "restart ssh"
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=ssh
    state=restarted
  ignore_errors: true
  
- name: restart ssh (via service)
  listen: "restart ssh"
  tags:
    - sssd
    - freeipaclient
  become: true
  service:
    name=ssh
    state=restarted
  ignore_errors: true
